name: Build
on:
  push:
    branches:
      - main

  pull_request:

jobs:
  job_build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - id: CHECKOUT_SOURCE_CODE
      name: Checkout source code
      uses: actions/checkout@v3

    - id: SETUP_JAVA_24
      name: Set up Java 24
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '24'

    - id: CONFIGURE_SQLCOMP
      name: Configure sqlcomp
      run: ./configure

    - id: BUILD_SQLCOMP
      name: Build sqlcomp
      run: make

    - id: TEST
      name: Test
      run: make testv
